### ISSUE TITLE
Fix Light/Dark Mode toggling on watch

### ISSUE THREAD

**Issue by gregorynewman12** [gregorynewman12/OutSafe#18]
Light/Dark mode seems to randomly toggle on the watch when a button is pushed. Determine why this is, and fix it.

**Comment by niranjanvarma6** [comment]
The reason why the toggling of the modes happened was because of the fillscreeen and the textcolor in our display.cpp file was switching colors. Hence to fix this for dark mode it is display.fillScreen(GxEPD_BLACK); and GxEPD_WHITE for light mode.
